"""Split the master table into one file per dictionary, and merge the Thai back.

Translation happens per dictionary because that is how the game groups strings, how the
work divides between people, and how a review stays reviewable.

    python tools/loc_split.py split     loc/source.tsv  -> loc/source/<name>.tsv
    python tools/loc_split.py merge     loc/th/*.tsv    -> plugin/.../Thai.tsv

Source files are `key <TAB> en <TAB> zh`. Thai files are `key <TAB> th`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def split(source: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    buckets: dict[str, list[str]] = {}

    with source.open(encoding="utf-8") as f:
        next(f)  # header
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 4:
                continue
            name, key, en, zh = parts[0], parts[1], parts[2], parts[3]
            buckets.setdefault(name, []).append(f"{key}\t{en}\t{zh}")

    for name, rows in sorted(buckets.items()):
        dest = out_dir / f"{name}.tsv"
        with dest.open("w", encoding="utf-8", newline="\n") as f:
            f.write("# key\tenglish\tchinese\n")
            f.write("\n".join(rows) + "\n")
        print(f"  {len(rows):>5}  {dest}")


def merge(th_dir: Path, dest: Path) -> None:
    rows: list[tuple[str, str]] = []
    seen: set[str] = set()
    duplicates = 0

    for path in sorted(th_dir.glob("*.tsv")):
        n = 0
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#"):
                continue
            key, _, value = line.partition("\t")
            if not value:
                continue
            if key in seen:
                duplicates += 1
                continue
            seen.add(key)
            rows.append((key, value))
            n += 1
        print(f"  {n:>5}  {path.name}")

    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# Pass the Fear - Thai\n")
        f.write("# key<TAB>value, UTF-8 no BOM, LF. '#' comments. Escapes: \\n \\t \\\\\n")
        f.write("# Generated by tools/loc_split.py - edit loc/th/*.tsv, not this file.\n\n")
        for key, value in rows:
            f.write(f"{key}\t{value}\n")

    print(f"\n{len(rows)} strings -> {dest}")
    if duplicates:
        print(f"  warning: skipped {duplicates} duplicate keys")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("mode", choices=["split", "merge"])
    ap.add_argument("--source", type=Path, default=Path("loc/source.tsv"))
    ap.add_argument("--source-dir", type=Path, default=Path("loc/source"))
    ap.add_argument("--th-dir", type=Path, default=Path("loc/th"))
    ap.add_argument("--out", type=Path, default=Path("plugin/PassTheFear.Thai/Thai.tsv"))
    args = ap.parse_args(argv)

    if args.mode == "split":
        split(args.source, args.source_dir)
    else:
        merge(args.th_dir, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
